### PR TITLE
Change redirection boxes

### LINKED ISSUE #2212: Redirect IDPF vocabularies
We need to redirect the old vocabularies that are hosted in IDPF's github space forward to the new spec.

They are all hosted here: https://github.com/IDPF/epub-vocabs

A meta refresh could be used to push people to the top of each vocabulary, or we may want to create a small javascript that gets the specific term they were trying to reach and appends it to a scripted redirect.

### PR DESCRIPTION
**Pull request by iherman**
This is to fix https://github.com/w3c/epub-specs/issues/2212

### CODE REVIEW

**Comment by mattgarrish** [comment]
Two nitpicks:

- The warning at the top is easily missed if someone is hyperlinking into a specific property. Is there any way we can steal the script that overlays obsolete w3c specs and warns users?
- The manual redirects would probably be better using TR/epub/ so we don't have to come back and update these again if there ever is a 3.4.

**Review by dauwhe — APPROVED** [review]

**Comment by iherman** [comment]
@mattgarrish @dauwhe the [A11y vocabulary](https://idpf.github.io/epub-vocabs/package/a11y/) has currently no redirection, so I did not touch that one. Is that all right?

**Comment by iherman** [comment]
@mattgarrish I looked into the scripts but I believe it is over-engineering what we need (and, personally, I think those TR warnings are obnoxious...:-).

What I did, instead, is to modify the style sheet to make the warning boxes' positioning fixed (and made a bit more visible with a khaki background). You can see the effects looking at the various items through:

https://iherman.github.io/epub-vocabs/

**Comment by mattgarrish** [comment]
> but I believe it is over-engineering for what we need

Ya, I woke up this morning and was going to say a jquery modal or even a javascript alert would be more than enough as these are just relics of IDPF. Making the warning stick works for me.

**Review by mattgarrish — APPROVED** [review]

**Comment by mattgarrish** [comment]
After you merge this, it'd probably be worthwhile to go into the settings and put the repository into archive mode.

We don't want people adding issues here.

**Comment by mattgarrish** [comment]
And if you want to keep tinkering, here are some more repositories of things that were previously split out that need obsolete markers and to be put into an archive state:

- Core media types: https://github.com/IDPF/epub-cmt
- Reserved prefixes: https://github.com/IDPF/epub-prefixes
- Registries: https://github.com/IDPF/epub-registries

**Comment by iherman** [comment]
@mattgarrish I do not have any administrative rights for this, or the other, IDPF repositories. I am happy to put this into archive mode, but you have to give me the authorization to do so first...

**Pull request merged**
